name: ci super app

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/*.java'
      - 'src/test/*.java'
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-actions@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v3
    
      - name: Build and test
        uses: docker/build-push-actions@v6
        with:
          target: test
          load: true
      
      - name: Build and push
        uses: docker/build-push-actions@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{vars.DOCKER_USERNAME}}/${{github.event.repository.name}}:latest
